### ISSUE TITLE
Support multiple databases in source connector

### ISSUE THREAD

**Issue by tomblench** [IBM/cloudant-kafka-connector#86]
Some data is partitioned across multiple cloudant databases, eg time series with one database per month or week etc.

We could support ingesting all of this data onto one kafka topic by allowing a _list_ of databases to be configured.

Issues to be addressed:

- Do we add a new a property, eg `cloudant.dbs` with a comma separated list
- If so, how does it interact with the existing `cloudant.db`
- These databases should be partitioned across tasks (analogous to how the [JDBC adaptor](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java#L154) partitions across tables

**Comment by ricellis** [comment]
In retrospect I think we decided that configuring multiple connectors was a suitable workaround for this that keeps the code simpler. @tomblench do you agree, shall we close?

**Comment by tomblench** [comment]
Agreed - we can always reopen if there is some demand for this, but multiple connector instances should be sufficient.
