### ISSUE TITLE
Connector moves and renames

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-kafka-connector#96]
Renames to allow for other endpoints in future (we'll get the cloudant part from the package name):
* `CloudantSourceConnector` -> `ChangesSourceConnector`
* `CloudantSinkConnector` -> `ChangesSinkConnector`

Put the "public" content in these packages
`com.ibm.cloud.cloudant.kafka.connect.connectors` (for the *SourceConnector and *SinkConnector classes)
`com.ibm.cloud.cloudant.kafka.connect.transforms` (for the transforms)
`com.ibm.cloud.cloudant.kafka.connect.transforms.predicates` (for the predicates)

Put the other content in a sensible set of sub-packages in 
`com.ibm.cloud.cloudant.kafka.connect.internal`

**Comment by mojito317** [comment]
As we discussed offline earlier: `CloudantSinkConnector` should not be renamed.
